import * as core from '@actions/core'
import * as exec from '@actions/exec'

export async function run(): Promise<void> {
  try {
    const gitOpts: string[] = ['status', '--porcelain']
    const skipUntracked = core.getInput('check_untracked') === 'false'
    if (skipUntracked) {
      gitOpts.push('-uno')
    }

    let output = ''
    const execOpts = {
      listeners: {
        stdout: (data: Buffer) => {
          output += data.toString()
        }
      }
    }

    await exec.exec('git', gitOpts, execOpts)

    if (output !== '') {
      let msg =
        'These files have changed since checkout. Check for out-of-sync autogenerated files'
      if (!skipUntracked) {
        msg += ', or for untracked files written inside the working tree'
      }
      core.setFailed(msg)
      core.startGroup('Full diff:')
      await exec.exec('git', ['diff'])
      core.endGroup()
    }
  } catch (error) {
    core.setFailed(error.message)
  }
}

run()
